### PR TITLE
Add AMP Working Group Logos

### PR DESCRIPTION
**Pull request by andrewwatterson**
Added a directory with the current set of AMP Working Group logos, as well as the Illustrator files used to generate them.

### CODE REVIEW

**Comment by andrewwatterson** [comment]
@Marcial1234 the logos (and original source file) are in here.

@mrjoro not sure if anyone actually gets notifications for this repo - let me know if you have any objections to merging this. people (well, person) are asking for them!

**Comment by mrjoro** [comment]
LGTM!

/cc @ampproject/tsc @cramforce in case there's a preference for putting these somewhere else

**Comment by andrewwatterson** [comment]
That's here, no? Merge it!

110djx

**Comment by cramforce** [comment]
Yes, I was obviously not awake yet 🥇

**Pull request merged**
