### PR TITLE
Creates a schedule for the ~quarterly Working Group updates

### PR DESCRIPTION
**Pull request by mrjoro**
This documents a schedule for the ~quarterly Working Group updates as described in #13.

Currently the Code of Conduct and Approvers WG are not included.

/cc @ampproject/tsc 

@jpettitt and @lannka as FYI since they would be the first two to present.

### CODE REVIEW

**Comment by lannka** [comment]
SGTM thanks for the heads up.
How long an update should we prepare?

**Comment by mrjoro** [comment]
This is the [WG member pages we wanted to generate](https://github.com/ampproject/docs/issues/1699)?  Interesting idea.

One tricky thing is to make sure that we account for weeks we skip due to holidays and the creation/modification/disbanding of working groups, but these aren't insurmountable.

@sebastianbenz WDYT?  How hard would it be to add this logic as part of the code that's generating the team list pages?  Basically we'd assign upcoming Design Review slots to each WG in a round-robin fashion.

Regarding @lannka's question, @cramforce do you have a sense of how long an update the @ampproject/tsc would like from the WGs?  I was thinking 10-15 minutes to leave the rest of the hour for the design review.

**Comment by cramforce** [comment]
10-15 minutes sounds good. And this can merge, of course, before we figure out a long-term plan.

**Comment by mrjoro** [comment]
@cramforce sgtm; can you approve the PR? :)

**Pull request merged**
