### PR TITLE
Add Performance Working Group

### PR DESCRIPTION
**Pull request by kristoferbaxter**
Adds a new Performance Working Group, whose mandate is to monitor and improve the load and runtime performance of AMP documents.

Two members are initially in the proposal, @kristoferbaxter (facilitator) and @prateekbh.

Skeleton for `@ampproject/wg-performance` has been created here (https://github.com/kristoferbaxter/wg-performance) and would be moved under the `@ampproject` repository namespace if the TSC agrees to the addition.

### CODE REVIEW

**Comment by nainar** [comment]
Hi @ampproject/tsc was there a discussion/resolution around the creation of this WG?

**Comment by cramforce** [comment]
Yes, I believe it was approved.

**Comment by nainar** [comment]
In that case can you create the group @cramforce? Thanks!

**Comment by cramforce** [comment]
@mrjoro Probably actually knows what to do :)

**Comment by nainar** [comment]
Pinging @mrjoro to create the needed WG

**Pull request merged**
