### PR TITLE
Clarify that AC advice to TSC is non-binding.

### LINKED ISSUE #10: Clarify the relationship between the AC and TSC
In his review @triblondon made the following comment:

> Expand the description of the AC's role to include detail on _how_ exactly it advises the TSC. For example, can the AC issue written findings? If they do, does the TSC have to adhere to them?

### PR DESCRIPTION
**Pull request by tobie**
Closes #10.

### CODE REVIEW

**Comment by mrjoro** [comment]
It looks like this never got reviewed/merged.  Is this still open?

/cc @ampproject/tsc @ampproject/ac

**Comment by davidstrauss** [comment]
I feel like the use of the term "advisory" already indicates that the guidance is non-binding.

**Comment by tobie** [comment]
I think this lightweight change clarifies a question that comes up regularly, and so I'd still like to have it included, for transparency.

**Comment by rudygalfi** [comment]
Can this be merged/resolved?

**Pull request merged**
